name: Run CI tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Run tests and Code Quality
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Initialize Python 3.7
        uses: actions/setup-python@v1

        with:
            python-version: 3.7

      - name: Run unittest
        run: |
          python setup.py test
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 apache_logs_parser --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 apache_logs_parser --count --max-complexity=10 --statistics


